"""Contains the ChatAgent class, responsible for managing the chat agent's interactions
with the language model and tools. It provides methods for streaming chat responses
and resuming after tool interrupts.
"""

from collections.abc import AsyncIterator, Sequence
from typing import Any

from langchain.agents import create_agent
from langchain.agents.middleware import HumanInTheLoopMiddleware
from langchain_core.messages import BaseMessage
from langgraph.types import Command


class ChatAgent:
    def __init__(
        self,
        model: str,
        tools: Sequence[Any],
        system_prompt: str,
        checkpointer: Any,
        middleware: Sequence[HumanInTheLoopMiddleware] | None = None,
    ) -> None:

        self.agent = create_agent(
            model=model,
            tools=tools,
            system_prompt=system_prompt,
            checkpointer=checkpointer,
            middleware=middleware,
        )

    async def stream(
        self, messages: Sequence[BaseMessage], thread_id: str
    ) -> AsyncIterator[dict[str, Any]]:
        """Main method for streaming chat responses.

        It takes a sequence of messages and a thread ID, and yields chunks of the
        response as they are generated by the language model.
        """
        async for event in self.agent.astream_events(
            {"messages": list(messages)},
            version="v2",
            config={
                "configurable": {
                    "thread_id": thread_id,
                }
            },
        ):
            event_type = event.get("event")

            # Handle different event types and yield appropriate responses

            # Handle tool start events
            if event_type == "on_tool_start":
                tool_name = event.get("name", "tool")
                tool_input = event.get("data", {}).get("input")
                content = f"Tool-Aufruf: {tool_name}"

                if tool_input:
                    content += f" ({tool_input})"

                yield {"type": "tool", "content": content}

            # Handle tool interrupts
            elif event_type == "on_chain_stream":
                chunk = event.get("data", {}).get("chunk", {})
                interrupts = chunk.get("__interrupt__", []) if isinstance(chunk, dict) else []

                if interrupts:
                    interrupt = interrupts[0]
                    interrupt_value = getattr(interrupt, "value", {})
                    action_requests = interrupt_value.get("action_requests", [])

                    yield {
                        "type": "interrupt",
                        "interrupt_id": getattr(interrupt, "id", ""),
                        "action_requests": action_requests,
                    }
            # Handle chat model stream events
            elif event_type == "on_chat_model_stream":
                chunk = event.get("data", {}).get("chunk")
                content = getattr(chunk, "content", "")

                if content:
                    yield {"type": "ai", "content": content[0]["text"]}

    async def resume(
        self,
        thread_id: str,
        interrupt_id: str,
        decisions: list[dict[str, Any]],
    ) -> AsyncIterator[dict[str, Any]]:
        """Resumes a chat after a tool interrupt.

        It takes a thread ID, an interrupt ID, and the decision made by the user,
        and yields chunks of the response as they are generated by the language model.
        """
        async for event in self.agent.astream_events(
            Command(resume={interrupt_id: {"decisions": decisions}}),
            version="v2",
            config={
                "configurable": {
                    "thread_id": thread_id,
                }
            },
        ):
            event_type = event.get("event")

            if event_type == "on_tool_start":
                tool_name = event.get("name", "tool")
                tool_input = event.get("data", {}).get("input")
                content = f"Tool-Aufruf: {tool_name}"

                if tool_input:
                    content += f" ({tool_input})"

                yield {"type": "tool", "content": content}

            elif event_type == "on_chat_model_stream":
                chunk = event.get("data", {}).get("chunk")
                content = getattr(chunk, "content", "")

                if content:
                    yield {"type": "ai", "content": content[0]["text"]}
